spring:
  jwt:
    secret: HelloMyNickNameIsBeHangAndNiceToMeetYouHowAreYouImFineThankYouAndYou

toss:
  secret-key: test_sk_ZORzdMaqN3wa1Zvl00br5AkYXQGw
  client-id: test_a8e23336d673ca70922b485fe806eb2d
  client-secret: test_418087247d66da09fda1964dc4734e453c7cf66a7a9e3
