spring:
  jwt:
    secret: HelloMyNickNameIsBeHangAndNiceToMeetYouHowAreYouImFineThankYouAndYou

toss:
  token: eyJraWQiOiJjZXJ0IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJ0ZXN0X2E4ZTIzMzM2ZDY3M2NhNzA5MjJiNDg1ZmU4MDZlYjJkIiwiYXVkIjoidGVzdF9hOGUyMzMzNmQ2NzNjYTcwOTIyYjQ4NWZlODA2ZWIyZCIsIm5iZiI6MTY3NjUyMTAwNSwic2NvcGUiOlsiY2EiXSwiaXNzIjoiaHR0cHM6XC9cL2NlcnQudG9zcy5pbSIsImV4cCI6MTcwODA1NzAwNSwiaWF0IjoxNjc2NTIxMDA1LCJqdGkiOiJmNTZlYTMxYS04N2MzLTQ2Y2EtOGIzZS0yYTA3NjNiOWJlM2MifQ.PRCFQoMBccrOzy19Cxgkj4F00j3hrdGG4HiVYQxve8JtPTHVAceQMxj92xYd6kcgvUk7N1mNFRYSLr3bqHGrmak4-tQWs8soQcdk_WVWF3IN0uzh51WMexLg-KgfnZrb_tPJDvTvsgwb2agaMSEUryeBaEGKub-cohPELSSkUqtUif6xKYq3Avd1HBKChHGqVelGYzs5mBtoUY0pT_dtXEg3rwghJ7jqCi6mE1hQks-a1l_Hh4T6NUnnAQXaKc72Ga2NHEdnzERgZNpQrJIAigWTB2JDqh13n2Sf66W8-ekzRNm2YpnMCPJN6D5yqzvgJNAa3LXOHW6jrfy4ql-t6w
  secret-key: live_sk_kZLKGPx4M3MawWW27Xe3BaWypv1o
  client-id: test_a8e23336d673ca70922b485fe806eb2d
  client-secret: test_418087247d66da09fda1964dc4734e453c7cf66a7a9e3
