
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dabom_dev?validationQuery="select 1"&useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: select 1 from dual

#springdoc:
#  api-docs:
#    enabled: true
#
#  swagger-ui:
#    display-request-duration: true  # try it out 을 했을 때 request duration 을 추가로 찍어줌
