spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dabom_dev?validationQuery="select 1"&useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: dabom
    password: Camp!@&webmaster!
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: select 1 from dual

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        enable_lazy_load_no_trans: true
        format_sql: true
        hbm2ddl:
          auto: create
    show-sql: true
    defer-datasource-initialization: true #더미데이터 용

  sql: #더미데이터 용
    init:
      mode: always
      data-locations: classpath:data.sql
      encoding: UTF-8
  data:
    redis:
      host: localhost
      port: 6379
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

  mail:
    host: smtp.gmail.com # SMTP 서버 호스트
    port: 587 # SMTP 서버 포트
    username: hansol8701 # SMTP 서버 로그인 아이디 (발신자)
    password: odjyssinswdqfafy # SMTP 서버 로그인 패스워드 (앱 비밀번호)
    properties:
      mail:
        smtp:
          auth: true # 사용자 인증 시도 여부 (기본값 : false)
          timeout: 5000 # Socket Read Timeout 시간(ms) (기본값 : 무한대)
          starttls:
            enable: true # StartTLS 활성화 여부 (기본값 : false)

logging:
  pattern:
    console: "%d{yy-MM-dd HH:mm:ss} %clr(%-5level) [%thread] %logger[%method:%line] - %msg%n"
    file: "%d{yy-MM-dd HH:mm:ss} %-5level [%thread] %logger[%method:%line] - %msg%n"
  logback:
    rollingpolicy:
      file-name-pattern: "C:/Dabom/logs/dev/%d{yy-MM-dd}/log_%i.zip"
      max-history: 30
      max-file-size: 20KB
      total-size-cap: 100MB
  level:
    root: info
    org.springframework: info
    org.hibernate:
      SQL: debug
      type: trace
  file:
    name: "C:/Dabom/logs/dev/current.log"

springdoc:
  use-fqn: true # 정규화된 스키마명 사용 설정
  api-docs:
    enabled: true
  swagger-ui:
    display-request-duration: true  # try it out 을 했을 때 request duration 을 추가로 찍어줌
    tags-sorter: alpha # @Tag를 알파벳 순으로 정렬

path:
  root: C:/Users/Administrator/Desktop/dabom/frontend/build
  images: /static/images
  videos: /static/videos

hls:
  ffmpeg: C:/ProgramData/chocolatey/bin/ffmpeg.exe
  ffprobe: C:/ProgramData/chocolatey/bin/ffprobe.exe